# Generated by Django 3.2.2 on 2024-03-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
